### DISCUSSION TITLE
Make it less linked to Puppet / PDK

### DISCUSSION THREAD

**Discussion by ahmet2mir** [puppetlabs-toy-chest/pct#153] [Feedback]
This is probably one of the best templating system I used but it's too linked to puppet.
This tool is just awesome and could bery useful for much more people than puppet communty :)

Commands like "new, convert, update" are not linked to pdk, but other "test, build release" etc are.

Is it possible to make them configurable from `pct-config.yml` ? so each "project" type will have their own test/build/release commands ?

For example if I have a makefile in the template I could define it as

```yaml
---
template:
  id: example-project2
  type: project
  display: Example Project
  version: 0.1.0
  url: https://github.com/somewhere

example_project2:
  build: make build
  test: make test
  release: make release
  variables:
    lorem: ipsum
```

You just "createCommand" from pct and exec it without relying on pdk.
